name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PKL_VERSION: 0.26.3
  HPKL_VERSION: 0.8.0

jobs:
  pkl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set version
        id: vars
        run: |
          [[ "$GITHUB_REF" =~ ^refs/tags/v.*$ ]] && echo "tag=${GITHUB_REF#refs/*/v}" >> $GITHUB_OUTPUT || echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT      
      - name: Create bin dir
        run: | 
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Download pkl-lang
        run: | 
          curl -sSL https://github.com/apple/pkl/releases/download/${PKL_VERSION}/pkl-linux-amd64 -o $HOME/.local/bin/pkl
          chmod +x $HOME/.local/bin/pkl
      - name: Replace baseUri
        run: |
          sed -i -e 's/package\:\/\/ghcr.io\/pklhub\/\\(name)/package\:\/\/pkg.hpkl.io\/\\(name)/g' PklProject
      - name: Build & Publish
        env:
          PROJECT_VERSION: ${{ steps.vars.outputs.tag }}      
        run: |
          pkl project resolve --no-cache
          pkl project package --no-cache
          gh release upload v$PROJECT_VERSION .out/k8s-app@$PROJECT_VERSION/k8s-app@$PROJECT_VERSION.zip
      - uses: actions/checkout@v4
        with:
          repository: pklhub/packages
          ref: 'main'
          token:  ${{ secrets.PUBLISH_TOKEN }}    
          path: 'packages'
      - name: Publish metadata
        env:
          PROJECT_VERSION: ${{ steps.vars.outputs.tag }}      
        run: |
          cp .out/k8s-app@$PROJECT_VERSION/hpkl-k8s-app@$PROJECT_VERSION packages/k8s-app@$PROJECT_VERSION
          cd packages
          git config --global user.email "ci@hpkl.io"
          git config --global user.name "Github Action"
          git add k8s-app@$PROJECT_VERSION
          git commit -m "Relase k8s-app@$PROJECT_VERSION"
          git push
  hpkl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set version
        id: vars
        run: |
          [[ "$GITHUB_REF" =~ ^refs/tags/v.*$ ]] && echo "tag=${GITHUB_REF#refs/*/v}" >> $GITHUB_OUTPUT || echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT      
      - name: Create bin dir
        run: | 
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Download pkl-lang
        run: | 
          curl -sSL https://github.com/apple/pkl/releases/download/${PKL_VERSION}/pkl-linux-amd64 -o $HOME/.local/bin/pkl
          chmod +x $HOME/.local/bin/pkl
      - name: Download hpkl
        run:  |
          curl -sSL https://github.com/pklhub/hpkl/releases/download/v${HPKL_VERSION}/hpkl_Linux_x86_64.tar.gz | tar -xz -C $HOME/.local/bin/ hpkl
      - name: Build & Publish
        env:
          PROJECT_VERSION: ${{ steps.vars.outputs.tag }}      
        run: |
          hpkl resolve
          hpkl package
          hpkl login -l ${{ github.actor }} -p ${{ secrets.PUBLISH_TOKEN }} ghcr.io
          hpkl publish
